name: Trigger Prod Update

on:
  push:
    branches:
      - main

jobs:
  trigger_update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Update in production
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN }}
          repository: rom88n/songs_lyrics_ci
          event-type: submodule-update
          client-payload: '{"service": "frontend"}'
